[package]
name = "riscbox"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
flate2 = { version = "1.1", default-features = false, features = ["rust_backend"] }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "deny"
pedantic = "deny"

[workspace]
members = [".", "riscbox-wasm"]
resolver = "3"
