[package]
name = "riscbox"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "rust/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
aes = { version = "0.9.3", default-features = false }
cbc = { version = "0.2.1", default-features = false, features = ["block-padding"] }
pbkdf2 = { version = "0.13.0", default-features = false, features = ["hmac"] }
sha2 = { version = "0.11.0", default-features = false }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
pedantic = "deny"

[workspace]
members = [".", "rust-wasm"]
resolver = "3"
